### ISSUE TITLE
The Wiki lacks documentation for Binary Stars and Biomes.

### ISSUE THREAD

**Issue by C1ffisme** [zmaster587/AdvancedRocketryDoc#3]
The Wiki lacks any documentation for making Binary Stars in planetDefs.xml. In addition to that, there is no documentation on the biomes added by Advanced Rocketry, such as the Hot Dry Rock, Alien Forest, Ocean Spires or Moon biomes.

Also, under the section "Gravitational Multiplier", the first sentence says:

The "gravitationalMultiplier" tag specifes the **density of the atmosphere** on a planet.

Not really an organized issue, but oh well.

**Comment by zmaster587** [comment]
The Binary star system is currently untested, and I do not believe it's yet backported to older builds, the gravitational multiplier thing I've fixed and I've merged the pull request.

**Comment by C1ffisme** [comment]
@zmaster587 Thanks!

I've tested the Binary Star thing and it seems to work with the 1.10.2 version, but I think further testing is best done before writing stuff down in the wiki.
